 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   entrypoint: bash
   secretEnv:
    - API_FIREBASE_TYPE
    - API_FIREBASE_PROJECT_ID
    - API_FIREBASE_PRIVATE_KEY_ID
    - API_FIREBASE_PRIVATE_KEY
    - API_FIREBASE_CLIENT_EMAIL
    - API_FIREBASE_CLIENT_ID
    - API_FIREBASE_AUTH_URI
    - API_FIREBASE_TOKEN_URI
    - API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL
    - API_FIREBASE_CLIENT_X509_CERT_URL
   args:
   - -c
   - |
    docker
    build
    --build-arg=FIREBASE_TYPE=$$API_FIREBASE_TYPE
    --build-arg=FIREBASE_PROJECT_ID=$$API_FIREBASE_PROJECT_ID
    --build-arg=FIREBASE_PRIVATE_KEY_ID=$$API_FIREBASE_PRIVATE_KEY_ID
    --build-arg=FIREBASE_PRIVATE_KEY=$$API_FIREBASE_PRIVATE_KEY
    --build-arg=FIREBASE_CLIENT_EMAIL=$$API_FIREBASE_CLIENT_EMAIL
    --build-arg=FIREBASE_CLIENT_ID=$$API_FIREBASE_CLIENT_ID
    --build-arg=FIREBASE_AUTH_URI=$$API_FIREBASE_AUTH_URI
    --build-arg=FIREBASE_TOKEN_URI=$$API_FIREBASE_TOKEN_URI
    --build-arg=FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$$API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL
    --build-arg=FIREBASE_CLIENT_X509_CERT_URL=$$API_FIREBASE_CLIENT_X509_CERT_URL
    -t gcr.io/$PROJECT_ID/server:$COMMIT_SHA .
  #  - build
  #  - --build-arg
  #  - FIREBASE_TYPE=$$API_FIREBASE_TYPE
  #  - --build-arg
  #  - FIREBASE_PROJECT_ID=$$API_FIREBASE_PROJECT_ID
  #  - --build-arg
  #  - FIREBASE_PRIVATE_KEY_ID=$$API_FIREBASE_PRIVATE_KEY_ID
  #  - --build-arg
  #  - FIREBASE_PRIVATE_KEY=$$API_FIREBASE_PRIVATE_KEY
  #  - --build-arg
  #  - FIREBASE_CLIENT_EMAIL=$$API_FIREBASE_CLIENT_EMAIL
  #  - --build-arg
  #  - FIREBASE_CLIENT_ID=$$API_FIREBASE_CLIENT_ID
  #  - --build-arg
  #  - FIREBASE_AUTH_URI=$$API_FIREBASE_AUTH_URI
  #  - --build-arg
  #  - FIREBASE_TOKEN_URI=$$API_FIREBASE_TOKEN_URI
  #  - --build-arg
  #  - FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$$API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL
  #  - --build-arg
  #  - FIREBASE_CLIENT_X509_CERT_URL=$$API_FIREBASE_CLIENT_X509_CERT_URL
  #  - -t
  #  - 'gcr.io/$PROJECT_ID/server:$COMMIT_SHA'
  #  - '.'
   
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/server:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'server'
   - '--image'
   - 'gcr.io/$PROJECT_ID/server:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
 images:
  - 'gcr.io/$PROJECT_ID/server:$COMMIT_SHA'
 availableSecrets:
  secretManager:
  - env: 'API_FIREBASE_TYPE'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_TYPE/versions/latest'
  - env: 'API_FIREBASE_PROJECT_ID'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_PROJECT_ID/versions/latest'
  - env: 'API_FIREBASE_PRIVATE_KEY_ID'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_PRIVATE_KEY_ID/versions/latest'
  - env: 'API_FIREBASE_PRIVATE_KEY'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_PRIVATE_KEY/versions/latest'
  - env: 'API_FIREBASE_CLIENT_EMAIL'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_CLIENT_EMAIL/versions/latest'
  - env: 'API_FIREBASE_CLIENT_ID'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_CLIENT_ID/versions/latest'
  - env: 'API_FIREBASE_AUTH_URI'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_AUTH_URI/versions/latest'
  - env: 'API_FIREBASE_TOKEN_URI'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_TOKEN_URI/versions/latest'
  - env: 'API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL/versions/latest'
  - env: 'API_FIREBASE_CLIENT_X509_CERT_URL'
    versionName: 'projects/$PROJECT_ID/secrets/API_FIREBASE_CLIENT_X509_CERT_URL/versions/latest'
