FROM python:3.8

ARG FIREBASE_TYPE
ARG FIREBASE_PROJECT_ID
ARG FIREBASE_PRIVATE_KEY_ID
ARG FIREBASE_PRIVATE_KEY
ARG FIREBASE_CLIENT_EMAIL
ARG FIREBASE_CLIENT_ID
ARG FIREBASE_AUTH_URI
ARG FIREBASE_TOKEN_URI
ARG FIREBASE_AUTH_PROVIDER_X509_CERT_URL
ARG FIREBASE_CLIENT_X509_CERT_URL

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./

RUN pip install -r requirements.txt

ENV PORT 8080
ENV API_FIREBASE_TYPE $FIREBASE_TYPE
ENV API_FIREBASE_PROJECT_ID $FIREBASE_PROJECT_ID
ENV API_FIREBASE_PRIVATE_KEY_ID $FIREBASE_PRIVATE_KEY_ID
ENV API_FIREBASE_PRIVATE_KEY $FIREBASE_PRIVATE_KEY
ENV API_FIREBASE_CLIENT_EMAIL $FIREBASE_CLIENT_EMAIL
ENV API_FIREBASE_CLIENT_ID $FIREBASE_CLIENT_ID
ENV API_FIREBASE_AUTH_URI $FIREBASE_AUTH_URI
ENV API_FIREBASE_TOKEN_URI $FIREBASE_TOKEN_URI
ENV API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL $FIREBASE_AUTH_PROVIDER_X509_CERT_URL
ENV API_FIREBASE_CLIENT_X509_CERT_URL $FIREBASE_CLIENT_X509_CERT_URL

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 main:app