name: cloudrun-deploy
on:
  push:
    branches:
      - main
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    env:
      API_FIREBASE_TYPE: ${{ secrets.API_FIREBASE_TYPE }}
      API_FIREBASE_PROJECT_ID: ${{ secrets.API_FIREBASE_PROJECT_ID }}
      API_FIREBASE_PRIVATE_KEY_ID: ${{ secrets.API_FIREBASE_PRIVATE_KEY_ID }}
      API_FIREBASE_PRIVATE_KEY: ${{ secrets.API_FIREBASE_PRIVATE_KEY }}
      API_FIREBASE_CLIENT_EMAIL: ${{ secrets.API_FIREBASE_CLIENT_EMAIL }}
      API_FIREBASE_CLIENT_ID: ${{ secrets.API_FIREBASE_CLIENT_ID }}
      API_FIREBASE_AUTH_URI: ${{ secrets.API_FIREBASE_AUTH_URI }}
      API_FIREBASE_TOKEN_URI: ${{ secrets.API_FIREBASE_TOKEN_URI }}
      API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.API_FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
      API_FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.API_FIREBASE_CLIENT_X509_CERT_URL }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
      
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1
      
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M